### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'chrX'

### ISSUE THREAD

**Issue by Gemma-Zhang-326** [XiaoTaoWang/pairLiftOver#6]
Hi, XiaoTao I am doing the validPairs liftOver by this wonderful tool. However, I encounterd an issue when I liftOver from rheMac10 which is the reference genome of rhesus Monkey to Hg38 genome. Here I paste my code up.
```
pairLiftOver --input merge.allValidPairs.gz --input-format pairs \
 --out-pre rheMac10tohg38_merge --output-format pairs --out-chromsizes hg38.chrom.sizes \
 --in-assembly rheMac10 --out-assembly hg38 \
 --chain-file rheMac10ToHg38.over.chain.gz --memory 40G --nproc 20 
```
The error it thrown is
```
root                      INFO    @ 11/29/22 10:17:38: 
# ARGUMENT LIST:
# Input path = merge.allValidPairs.gz
# Input format = pairs
# Output prefix = rheMac10tohg38_H3K27ac_merge
# Output format = pairs
# Chromosome Sizes of the output assembly = hg38.chrom.sizes
# Generate contact maps at 11 resolutions = False
# Input assembly = rheMac10
# Output assembly = hg38
# Chain file = rheMac10ToHg38.over.chain.gz
# Temporary Dir = .pairliftover
# Allocated memory = 40G
# Number of Processes = 20
# Log file name = pairLiftOver.log
pairLiftOver.utilities    INFO    @ 11/29/22 10:17:54: Writing headers ...
pairLiftOver.utilities    INFO    @ 11/29/22 10:18:44: Converting, sorting, and compressing ...
Traceback (most recent call last):
  File "/gpfs/home/anaconda3/envs/pairliftover/bin/pairLiftOver", line 137, in <module>
    run()
  File "/gpfs/home/anaconda3/envs/pairliftover/bin/pairLiftOver", line 123, in run
    liftover(
  File "/gpfs/home/anaconda3/envs/pairliftover/lib/python3.9/site-packages/pairLiftOver/utilities.py", line 187, in liftover
    total_count, mapped_count = _pairs_write(stdin_wrapper,
  File "/gpfs/home/anaconda3/envs/pairliftover/lib/python3.9/site-packages/pairLiftOver/io.py", line 246, in _pairs_write
    p1_, p2_ = int(p1_), int(p2_)
ValueError: invalid literal for int() with base 10: 'chrX'
```
And the log file
```
# ARGUMENT LIST:
# Input path = merge.allValidPairs.gz
# Input format = pairs
# Output prefix = rheMac10tohg38_merge
# Output format = pairs
# Chromosome Sizes of the output assembly = hg38.chrom.sizes
# Generate contact maps at 11 resolutions = False
# Input assembly = rheMac10
# Output assembly = hg38
# Chain file = rheMac10ToHg38.over.chain.gz
# Temporary Dir = .pairliftover
# Allocated memory = 40G
# Number of Processes = 20
# Log file name = pairLiftOver.log
pairLiftOver.utilities    INFO    @ 11/29/22 10:17:54: Writing headers ...
pairLiftOver.utilities    INFO    @ 11/29/22 10:18:44: Converting, sorting, and compressing ...
```
Really need help! Looking forward for your reply sincerely.

**Comment by XiaoTaoWang** [comment]
Hi, if your input is allValidPairs from HiC-Pro, you need to change the input format accordingly by specifying ``--input-format hic-pro``. Also refer to help information of other arguments through ``pairLiftOver -h``.

**Comment by Gemma-Zhang-326** [comment]
> Hi, if your input is allValidPairs from HiC-Pro, you need to change the input format accordingly by specifying `--input-format hic-pro`. Also refer to help information of other arguments through `pairLiftOver -h`.

Silly me! Thanks for your reply. It has been solved as you said.
